baseURL: https://indi.bio
languageCode: en-us
title: indi.bio
theme: "Paper++"

params:
  homeInfoParams:
    Title: indi.bio
    Content: "*a digital garden*  ðŸŒ±"

  socialIcons: # optional
    - name: "github"
      url: "https://github.com/tealblu"
    # - name: "youtube"
    #   url: "https://www.youtube.com/channel/XXX"
    - name: "bluesky"
      url: "https://bsky.app/profile/indi.tgirl.gay"
    - name: "matrix"
      url: "https://matrix.to/#/@indiharts:matrix.org"
    - name: "rss"
      url: "https://www.indi.bio/index.xml"
  author: "indigo hartsell"
  contact:
    email: "indiharts@proton.me"
  feedlinks: true
  copyright: "<!--MIT License-->This site is licensed under the [MIT License](https://opensource.org/licenses/MIT).<!--/MIT License-->"
  mobileMenu: true
  ShowShareButtons: true # toggle share buttons
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowCodeCopyButtons: true

  navModule:
    interval: 10000
    ariaLabel: "Rotate status messages"
    weather:
      enabled: true
      location: "Chicago, IL"
      units: "imperial"
      label: ""
    messages:
      - text: "Tending the digital garden."
      - text: "Cracking anti-repair code."
      - text: "Playing with my cat."

  googlefonts: "//fonts.googleapis.com/css?family=Fira+Mono|Fira+Sans"

  cover:
    linkFullImages: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

menu:
  main:
    - identifier: about
      name: about
      url: /about/
      weight: 1
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: archive
      name: archive
      url: /archives/
      weight: 30
    - identifier: search
      name: search
      url: /search/
      weight: 40

